---
title: "Maiko's Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: minty
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(rio)
library(knitr)
library(gt)
library(DT)
library(reactable)
library(gtsummary)
library(kableExtra)
library(tinytex)
library(janitor)
library(tidylog)
library(sjPlot)
library(lme4)
library(tibble)
library(dplyr)
library(epitools)
library(readxl)
library(pwr)
library(rcompanion)
library(grateful)
library(distill)
library(readxl)
library(scales)
library(tidyr)
library(patchwork)
library(corrplot)
library(distill)
library(tibble)
library(rcartocolor)
library(ggplot2)
library(ggforce)
library(ggrepel)
library(gghighlight)
library(quarto)
library(epitools)
library(plotly)
library(gapminder)
library(flexdashboard)
library(usethis)
```

```{r include=FALSE}
# read cvs etc. 
```

Project background: {.sidebar}
===============
This is a project _________. The datasets are downloaded from the Office of Special Education  [OSEP](https://data.ed.gov/dataset/idea-section-618-data-products-static-tables-part-c)

# Maiko's data visualizations 



Column {data-width=650}
-----------------------------------------------------------------------
### Final Visualization 

```{r}

```

```{r}
# read.csv and such 
```

{.sidebar}

Column {data-width=650}
-----------------------------------------------------------------------

### Second Attempt 

```{r}
p2 <- ggplot(gapminder, aes(year, lifeExp, group = country)) +
  geom_line(color = "blue", alpha = 0.5) +
  labs(title = "Life Expectancy Trends", y = "Life Expectancy", x = "Year")

p2
```

### First Attempt 

```{r}
p2 <- ggplot(gapminder, aes(year, lifeExp, group = country)) +
  labs(title = "Life Expectancy Trends", y = "Life Expectancy", x = "Year")

p2
```

